etheno/__init__.py
etheno/__main__.py
etheno/client.py
etheno/etheno.py
etheno/ganache.py
etheno/geth.py
etheno/synchronization.py
etheno/utils.py
setup.py

Support for Geth as an Etheno client

---

etheno/__main__.py
etheno/client.py
etheno/etheno.py
etheno/geth.py
etheno/synchronization.py
etheno/utils.py

Synchronizes account addresses, contract addresses, transaction hashes, and filter IDs between clients, even if they are on different chains. (#2)

Synchronize transactions between chains

---

etheno/__init__.py
etheno/__main__.py
etheno/client.py
etheno/differentials.py
etheno/etheno.py
etheno/synchronization.py

Automatically compare contract creation and gas use among all clients. See Issue #3.

Differential testing

---

etheno/__main__.py
etheno/client.py
etheno/genesis.py
etheno/geth.py
etheno/utils.py

Support for loading and saving genesis files

---

etheno/client.py
etheno/differentials.py
etheno/echidna.py
etheno/etheno.py
etheno/synchronization.py

See #20.
This PR also includes various bug fixes and improvements for address synchronization and differential testing.

Estimate gas costs before generating transactions

---

etheno/__main__.py
etheno/client.py
etheno/differentials.py
etheno/echidna.py
etheno/etheno.py
etheno/ganache.py
etheno/geth.py
etheno/logger.py
etheno/synchronization.py
etheno/truffle.py
examples/BrokenMetaCoin/ExploitMetaCoinManticoreScript.py
setup.py

Switch to Pythonic logging and colorized terminal output

---

etheno/__main__.py
etheno/genesis.py
etheno/geth.py
etheno/keyfile.py
etheno/logger.py
etheno/parity.py
etheno/synchronization.py
setup.py

Adds Parity as an Etheno client. See #16.

Support for Parity

---

etheno/__main__.py
etheno/genesis.py

Set EIP and fork blocks in the default genesis and from the command line

---

etheno/differentials.py
etheno/echidna.py
etheno/etheno.py
etheno/geth.py
etheno/jsonrpcclient.py
etheno/logger.py
etheno/parity.py

API to allow clients and plugins to save log files

---

Dockerfile
README.md
setup.py

Update the install

---

etheno/etheno.py
etheno/logger.py
etheno/truffle.py
examples/BrokenMetaCoin/contracts/ConvertLib.sol
examples/BrokenMetaCoin/contracts/MetaCoin.sol
examples/BrokenMetaCoin/contracts/Migrations.sol
examples/BrokenMetaCoin/run_etheno.sh

Update the examples to work with solc v0.5.0+

---

etheno/__main__.py
etheno/truffle.py

Adds an option for a custom build command

---

etheno/__main__.py

Properly honor the `--ganache-args` option

---

etheno/__main__.py
etheno/jsonrpc.py

See #59.
This also adds JSON RPC results, resolving #57.

Export an event summary

---

CHANGELOG.md
Dockerfile
etheno/echidna.py
etheno/etheno.py
etheno/genesis.py
examples/ConstantinopleGasUsage/constantinople.sol
setup.py

The features haven't been merged into Echidna master yet (that will hopefully happen before the next Etheno release), but this at least provides support for a much newer version of Echidna.

Preliminary support for the Echidna refactor

---

etheno/manticoreutils.py

Fixes the Manticore version check

---

etheno/manticoreutils.py

Addresses a callback that was renamed in Manticore 0.3.0

---

etheno/manticoreclient.py
etheno/manticoreutils.py
examples/BrokenMetaCoin/truffle-config.js

Changes were required to support the latest version of Manticore (v0.3.0).

Fixes the BrokenMetaCoin example

---

.github/workflows/docker.yml
.github/workflows/pythonpublish.yml
Dockerfile

Reduces Docker container size and adds GitHub actions for deploying to DockerHub and PyPI

Docker improvements

---

README.md

Added a warning about ganache compatibility with Node 14

---

etheno/jsonrpc.py

Export evm_mine and evm_increaseTime as the ContractCreated event

---

etheno/jsonrpc.py

This happens with simple eth transfer transactions.

Use "0x00" as data if there is no data in the transaction.
